/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;

/**
 *
 * @author khond
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    calculadora.Calculo cal = new calculadora.Calculo();
    calculadora.CalculoBinario calbin = new calculadora.CalculoBinario();
    calculadora.CalculoOctal caloctal = new calculadora.CalculoOctal();
    calculadora.CalculoHexadecimal calhex = new calculadora.CalculoHexadecimal();
    calculadora.NumeroSis convertir = new calculadora.NumeroSis();
    String operacion;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PanelDecimalBTN = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        jComboBoxSistemanumerico = new javax.swing.JComboBox<>();
        Display = new javax.swing.JTextField();
        PanelDecimalBTN1 = new javax.swing.JPanel();
        btn10 = new javax.swing.JButton();
        btnresultado = new javax.swing.JButton();
        btndividir = new javax.swing.JButton();
        btnmultiplicacion = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        PanelDecimalBTN.setBackground(new java.awt.Color(0, 0, 0));
        PanelDecimalBTN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnD.setBackground(new java.awt.Color(255, 255, 255));
        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(255, 255, 255));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnB.setBackground(new java.awt.Color(255, 255, 255));
        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnA.setBackground(new java.awt.Color(255, 255, 255));
        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnF.setBackground(new java.awt.Color(255, 255, 255));
        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(255, 255, 255));
        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDecimalBTNLayout = new javax.swing.GroupLayout(PanelDecimalBTN);
        PanelDecimalBTN.setLayout(PanelDecimalBTNLayout);
        PanelDecimalBTNLayout.setHorizontalGroup(
            PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDecimalBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDecimalBTNLayout.createSequentialGroup()
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelDecimalBTNLayout.createSequentialGroup()
                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDecimalBTNLayout.setVerticalGroup(
            PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDecimalBTNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnD)
                        .addComponent(btnE))
                    .addGroup(PanelDecimalBTNLayout.createSequentialGroup()
                        .addComponent(btnB)
                        .addGap(18, 18, 18)
                        .addComponent(btnC)
                        .addGap(43, 43, 43))
                    .addGroup(PanelDecimalBTNLayout.createSequentialGroup()
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7)
                            .addComponent(btn8)
                            .addComponent(btn9)
                            .addComponent(btnA))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4)
                            .addComponent(btn5)
                            .addComponent(btn6))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1)
                            .addComponent(btn2)
                            .addComponent(btn3))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDecimalBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0)
                            .addComponent(btnF))))
                .addGap(43, 43, 43))
        );

        jComboBoxSistemanumerico.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxSistemanumerico.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxSistemanumerico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DECIMAL", "BINARIO", "OCTAL", "HEXADECIMAL" }));
        jComboBoxSistemanumerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSistemanumericoActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(204, 204, 204));
        Display.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        PanelDecimalBTN1.setBackground(new java.awt.Color(0, 0, 0));
        PanelDecimalBTN1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn10.setBackground(new java.awt.Color(0, 0, 204));
        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setText("c");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btnresultado.setBackground(new java.awt.Color(255, 255, 0));
        btnresultado.setText("=");
        btnresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresultadoActionPerformed(evt);
            }
        });

        btndividir.setBackground(new java.awt.Color(255, 0, 0));
        btndividir.setForeground(new java.awt.Color(255, 255, 255));
        btndividir.setText("/");
        btndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividirActionPerformed(evt);
            }
        });

        btnmultiplicacion.setBackground(new java.awt.Color(0, 255, 204));
        btnmultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        btnmultiplicacion.setText("*");
        btnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicacionActionPerformed(evt);
            }
        });

        btnsuma.setBackground(new java.awt.Color(102, 255, 0));
        btnsuma.setForeground(new java.awt.Color(255, 255, 255));
        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });

        btnresta.setBackground(new java.awt.Color(102, 51, 255));
        btnresta.setForeground(new java.awt.Color(255, 255, 255));
        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDecimalBTN1Layout = new javax.swing.GroupLayout(PanelDecimalBTN1);
        PanelDecimalBTN1.setLayout(PanelDecimalBTN1Layout);
        PanelDecimalBTN1Layout.setHorizontalGroup(
            PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDecimalBTN1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDecimalBTN1Layout.createSequentialGroup()
                        .addComponent(btnsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnresta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDecimalBTN1Layout.createSequentialGroup()
                        .addComponent(btnmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDecimalBTN1Layout.setVerticalGroup(
            PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDecimalBTN1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndividir)
                    .addComponent(btnmultiplicacion)
                    .addComponent(btnsuma)
                    .addComponent(btnresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDecimalBTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10)
                    .addComponent(btnresultado))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelDecimalBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Display, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSistemanumerico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDecimalBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxSistemanumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDecimalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDecimalBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void iniciarDisplay() {
        if (Display.getText().equals("0")) {
            Display.setText("");
        }
        
    }
    
    private void Botones() {
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                Display.setText("");
                cal.setNumero1(0);
                cal.setNumero2(0);
                btn0.setVisible(true);
                btn1.setVisible(true);
                btn2.setVisible(true);
                btn3.setVisible(true);
                btn4.setVisible(true);
                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);
                btnA.setVisible(false);
                btnB.setVisible(false);
                btnC.setVisible(false);
                btnD.setVisible(false);
                btnE.setVisible(false);
                btnF.setVisible(false);
                break;
            case 1:
                Display.setText("");
                cal.setNumero1(0);
                cal.setNumero2(0);
                btn0.setVisible(true);
                btn1.setVisible(true);
                btn2.setVisible(false);
                btn3.setVisible(false);
                btn4.setVisible(false);
                btn5.setVisible(false);
                btn6.setVisible(false);
                btn7.setVisible(false);
                btn8.setVisible(false);
                btn9.setVisible(false);
                btnA.setVisible(false);
                btnB.setVisible(false);
                btnC.setVisible(false);
                btnD.setVisible(false);
                btnE.setVisible(false);
                btnF.setVisible(false);
                break;
            case 2:
                Display.setText("");
                cal.setNumero1(0);
                cal.setNumero2(0);
                btn0.setVisible(true);
                btn1.setVisible(true);
                btn2.setVisible(true);
                btn3.setVisible(true);
                btn4.setVisible(true);
                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(false);
                btn9.setVisible(false);
                btnA.setVisible(false);
                btnB.setVisible(false);
                btnC.setVisible(false);
                btnD.setVisible(false);
                btnE.setVisible(false);
                btnF.setVisible(false);
                break;
            case 3:
                Display.setText("");
                cal.setNumero1(0);
                cal.setNumero2(0);
                btn0.setVisible(true);
                btn1.setVisible(true);
                btn2.setVisible(true);
                btn3.setVisible(true);
                btn4.setVisible(true);
                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);
                btnA.setVisible(true);
                btnB.setVisible(true);
                btnC.setVisible(true);
                btnD.setVisible(true);
                btnE.setVisible(true);
                btnF.setVisible(true);
                break;
            default:
                break;
        }
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        
        Display.setText(Display.getText() + btn7.getText());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                if (!"".equals(Display.getText())) {
                    cal.setNumero1(Integer.parseInt(Display.getText()));
                }
                
                operacion = "+";
                Display.setText("");
                break;
            case 1:
                if (!"".equals(Display.getText())) {
                    calbin.setNumero1(Integer.parseInt(Display.getText()));
                }
                operacion = "+";
                Display.setText("");
                break;
            case 2:
                if (!"".equals(Display.getText())) {
                    caloctal.setNumero1(Integer.parseInt(Display.getText()));
                }
                operacion = "+";
                Display.setText("");
                break;
            case 3:
                if (!"".equals(Display.getText())) {
                    calhex.setNumero1(Display.getText());
                }
                operacion = "+";
                Display.setText("");
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnsumaActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        
        Display.setText(Display.getText() + btn8.getText());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        
        Display.setText(Display.getText() + btn9.getText());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        
        Display.setText(Display.getText() + btn4.getText());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        
        Display.setText(Display.getText() + btn5.getText());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        
        Display.setText(Display.getText() + btn6.getText());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        Display.setText(Display.getText() + btn1.getText());

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        Display.setText(Display.getText() + btn2.getText());

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        
        Display.setText(Display.getText() + btn3.getText());

    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        
        Display.setText(Display.getText() + btn0.getText());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                if (!"".equals(Display.getText())) {
                    cal.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "-";
                break;
            case 1:
                if (!"".equals(Display.getText())) {
                    calbin.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "-";
                break;
            case 2:
                if (!"".equals(Display.getText())) {
                    caloctal.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "-";
                break;
            case 3:
                if (!"".equals(Display.getText())) {
                    calhex.setNumero1(Display.getText());
                    Display.setText("");
                }
                operacion = "-";
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicacionActionPerformed
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                if (!"".equals(Display.getText())) {
                    cal.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "*";
                break;
            case 1:
                if (!"".equals(Display.getText())) {
                    calbin.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "*";
                break;
            case 2:
                if (!"".equals(Display.getText())) {
                    caloctal.setNumero1(Integer.parseInt(Display.getText()));
                    Display.setText("");
                }
                operacion = "*";
                break;
            case 3:
                if (!"".equals(Display.getText())) {
                    calhex.setNumero1(Display.getText());
                    Display.setText("");
                }
                operacion = "*";
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnmultiplicacionActionPerformed

    private void btndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividirActionPerformed
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                if (!"".equals(Display.getText())) {
                    cal.setNumero1(Integer.parseInt(Display.getText()));
                }
                Display.setText("");
                operacion = "/";
                break;
            case 1:
                if (!"".equals(Display.getText())) {
                    calbin.setNumero1(Integer.parseInt(Display.getText()));
                }
                Display.setText("");
                operacion = "/";
                break;
            case 2:
                if (!"".equals(Display.getText())) {
                    caloctal.setNumero1(Integer.parseInt(Display.getText()));
                }
                Display.setText("");
                operacion = "/";
                break;
            case 3:
                if (!"".equals(Display.getText())) {
                    calhex.setNumero1(Display.getText());
                }
                Display.setText("");
                operacion = "/";
                break;
            default:
                break;
        }
        

    }//GEN-LAST:event_btndividirActionPerformed

    private void btnresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresultadoActionPerformed
        
        switch (jComboBoxSistemanumerico.getSelectedIndex()) {
            case 0:
                if (!"".equals(Display.getText())) {
                    
                        cal.setNumero2(Integer.parseInt(Display.getText()));
                        
                        switch (operacion) {
                            case "+":
                                cal.sumar();
                                break;
                            case "-":
                                cal.restar();
                                break;
                            case "*":
                                cal.multiplicar();
                                break;
                            case "/":
                                cal.dividir();
                                break;
                            default:
                                break;
                        }
                        Display.setText(String.valueOf(cal.getResultado()));
                   
                }
                break;
            case 1:
                if (!"".equals(Display.getText())) {
                    calbin.setNumero2(Integer.parseInt(Display.getText()));
                    
                    switch (operacion) {
                        case "+":
                            calbin.sumar();
                            break;
                        case "-":
                            calbin.restar();
                            break;
                        case "*":
                            calbin.multiplicar();
                            break;
                        case "/":
                            calbin.dividir();
                            break;
                        default:
                            break;
                    }
                    Display.setText(String.valueOf(calbin.getResultado()));
                }
                break;
            case 2:
                if (!"".equals(Display.getText())) {
                    caloctal.setNumero2(Integer.parseInt(Display.getText()));
                    switch (operacion) {
                        case "+":
                            caloctal.sumar();
                            break;
                        case "-":
                            caloctal.restar();
                            break;
                        case "*":
                            caloctal.multiplicar();
                            break;
                        case "/":
                            caloctal.dividir();
                            break;
                        default:
                            break;
                    }
                    Display.setText(String.valueOf(caloctal.getResultado()));
                }
                break;
            case 3:
                if (!"".equals(Display.getText())) {
                    calhex.setNumero2(Display.getText());
                    switch (operacion) {
                        case "+":
                            calhex.sumar();
                            break;
                        case "-":
                            calhex.restar();
                            break;
                        case "*":
                            calhex.multiplicar();
                            break;
                        case "/":
                            calhex.dividir();
                            break;
                        default:
                            break;
                    }
                    Display.setText(calhex.getResultadoo());
                }
                break;
            default:
                break;
        }
        

    }//GEN-LAST:event_btnresultadoActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        Display.setText("");
        cal.setNumero1(0);
        cal.setNumero2(0);

    }//GEN-LAST:event_btn10ActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        Display.setText(Display.getText() + btnD.getText());
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        Display.setText(Display.getText() + btnE.getText());
    }//GEN-LAST:event_btnEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        Display.setText(Display.getText() + btnC.getText());
    }//GEN-LAST:event_btnCActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        Display.setText(Display.getText() + btnF.getText());
    }//GEN-LAST:event_btnFActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        Display.setText(Display.getText() + btnB.getText());
    }//GEN-LAST:event_btnBActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        Display.setText(Display.getText() + btnA.getText());
    }//GEN-LAST:event_btnAActionPerformed

    private void jComboBoxSistemanumericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSistemanumericoActionPerformed
        Botones();
    }//GEN-LAST:event_jComboBoxSistemanumericoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Botones();

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JPanel PanelDecimalBTN;
    private javax.swing.JPanel PanelDecimalBTN1;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btndividir;
    private javax.swing.JButton btnmultiplicacion;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnresultado;
    private javax.swing.JButton btnsuma;
    private javax.swing.JComboBox<String> jComboBoxSistemanumerico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
